import {STUFF_CHANGED} from './actions';

const reducer = function(state, action) {
    if (state === undefined){
        return  {
            zebra : {},
            temp_zebra : {
                "accuracy": 80.0,
                "address": "lakeville, MN 55044",
                "address2": null,
                "advert_variation_results": {
                    "2": {
                        "f": [{
                            "advert_position": 0,
                            "advert_priority": 1,
                            "advert_variation": 2,
                            "analytics_category": "Ads - Katch",
                            "best_seller_rank": 0,
                            "carrier_description": "",
                            "carrier_display_name": "Allstate",
                            "carrier_estimate_phone_number": null,
                            "carrier_featured_text": "Safe Drivers Choose Allstate&reg;",
                            "carrier_features": ["<ul><li>Safe Drivers Can Save Up To 45% On Their Auto Insurance</li><li>Get Two Safe Driver Bonus Checks a Year</li><li>Quote Online & Start Saving Today!</li></ul>"],
                            "carrier_icon": null,
                            "carrier_id": "katch",
                            "carrier_is_featured": false,
                            "carrier_legal_name": "Allstate",
                            "carrier_logo": "//cdn.katch.com/logos/adv_34807_401.gif?e=427ae720-1ebe-4044-af73-7a8c02384b1c_576186&pos=1",
                            "carrier_official_website": "www.Allstate.com",
                            "down_payment": 0,
                            "impression_html": "<img class=\"be_impr_html\" src=\"/be/i/t/?k=fc22465b-5874-41ce-a111-7ff3ea0597d1&al=f&ap=1&quote_id=5947e22ceff81d56b4a9e2e7\" />",
                            "insurance_product_id": null,
                            "insurance_product_name": null,
                            "insurance_product_not_match": false,
                            "is_advert": true,
                            "is_computed": false,
                            "is_coverage_mismatch": false,
                            "last_modified": "2017-06-22T09:39:27.565208",
                            "monetization_strategy": 4,
                            "monthly_estimate": 0,
                            "monthly_estimate_sub_text": "",
                            "purchase_method_affiliate_link": "/be/a/t/?p=k&r=FZqg3gZ2tQW-_lPAXYSt94D2jJPHZOWN-8aEqWH6NOvN3MRVCtrYCRBSrp1rXtD8fKmMEPcstMAbdjic33jn3vxTNkrlfH6MJVz55ljgbzp9oQIEHDko0CWT93lJYtavAutRzopPYt1-vaN0wRvFkNxk8LT_UO0O1twj3DNa5EYbNxvWCizF7QlqSi3dbINfIKLsTykVgIibj3E5bsHxIfUooR4yn1YacIPs_smK8sNA2iGmow3abyrlLAbh-X3Ut4NoYkDjXGRsmhjqsYC6dHxZ3fIh9BhGhT0tPIVhtAFb9hlY9NaXWtb1beXgN_epaZ0DHXt1fTHiSj82QT8jFWa3CivmUqKujgxiofovOwWmAzajwVVSakleN_OTL8YGbt64nIpCDmu8QRc1oGVph341lU7os1kGmSrltv3uPyosIlJuEWTwd8ECCIKQSVBSrjllDmN6loLOrncU55jI9vPkM15fLN2Th_mVqMYLcML7UTpbDIzAm8t6crewUPeUR_HQneKbIgrIQ2yA40p6oo45HzQQr6PP0gDLCcOjNCR31y8tojyxn1Bl849BINCqzS9RY_iETJSrpHJS-F5LlfkU9eKTteqa-97qP95KpHbeBT5nXeYzJKYEVql7f6EPXzIh2_AbnWjU8BoOPRYO8Go2LZf8u_Uk4XSPbBCtwviJ0DR1r3hexxWRc54JdhBfvRHcOcV2RVZmJZge9tfaNhptCJIEFFoRdvfYonbvQRYRsCrUlzSpf9qh60nBnIiNUDPlWoYWlfwF5CjaOi5n1BiueRquqzfIypAMZbG26ll0heYLVBQs9GtHCHYUlFNtFwbP69XfJP9RU4bm0wLp5cRx4wJEJx_bxv711qHSX1lQ8Vp2hGuy_9xGXdzMadUsV3_r7A-Kfhk6grAaRGMRj4V3hsag-cL72EcabuVMGXhSJ5a9ppL0Uf0qb7YPY7hjbW0XuOI_O3aSMYHNOpO7aa8jlDpQmRc7Pw1AeKmfvcDs3ZKpSFscnZmNu0rimGTTEruStR0QkVnIG3sso8eD5MEc5YzUv19GxxgmUqVyJLDtRULHDE_eI08m2OxHw8S73sydPZu59oPISo8NZ0ZQyqCc-YcGOI5sSycnMlm2NMn1k8BCjIP3gKBVaKJQ3sbvN1WuVVEcq4yHUSoScygT-uHFHUEjPoCgA8UXv3s6YvwYIA4pmlz-le9FacCtEu-YpnCIiOA2x76zuYzzVykBWhvcLjo5xzQ8LfDdHwNGNTQ=&k=hkWG-hgXU8VW-hH0vNZMOJEf13HPMcbmgN5aOmVzWZQEwJSJn0lVGMvfERf8WvzE&al=f&ap=1",
                            "rate_source": 7,
                            "rendering_key": "fc22465b-5874-41ce-a111-7ff3ea0597d1",
                            "replaces_carrier_id": 32,
                            "semi_annual_estimate": 0
                        }, {
                            "advert_position": 0,
                            "advert_priority": 1,
                            "advert_variation": 2,
                            "analytics_category": "Ads - MediaAlphaZebra",
                            "best_seller_rank": 0,
                            "carrier_description": "",
                            "carrier_display_name": "Esurance",
                            "carrier_estimate_phone_number": null,
                            "carrier_featured_text": "You Could Save with Esurance!",
                            "carrier_features": ["Minnesota Drivers - See If You Can Save Today<br>We've Insured Over 5 million Vehicles Since 1999<br>24/7 Claims Service - Located in the USA"],
                            "carrier_icon": null,
                            "carrier_id": "media_alpha",
                            "carrier_is_featured": false,
                            "carrier_legal_name": "Esurance",
                            "carrier_logo": "//d29u10q7qlh006.cloudfront.net/i/i/13/O2yQ5N5zaCrNIkKKJPX4MUykeew.png",
                            "carrier_official_website": "www.esurance.com",
                            "down_payment": 0,
                            "impression_html": "<img class=\"be_impr_html\" src=\"/be/i/t/?k=f080a35d-de44-4879-a906-079a2a52ab36&al=f&ap=2&quote_id=5947e22ceff81d56b4a9e2e7\" />",
                            "insurance_product_id": null,
                            "insurance_product_name": null,
                            "insurance_product_not_match": false,
                            "is_advert": true,
                            "is_computed": false,
                            "is_coverage_mismatch": false,
                            "last_modified": "2017-06-22T09:39:27.565553",
                            "monetization_strategy": 4,
                            "monthly_estimate": 0,
                            "monthly_estimate_sub_text": "",
                            "purchase_method_affiliate_link": "/be/a/t/?p=maz&r=IZCpvuh31KdcWPjeNGAAQzMhRiPEA2WmPRopeb9u-Qt-YRwV9RRburtu7RnwxI3k2rqOmhhR8IiMYfXEL40VpX_ijFZl4g96sAEXguaRm0mYesLjeHzg-_HN18appFmI63n8WRKU7tTkvknvaA056BE2U5asuZwGn6LC-sP266PbvyQrzasZeEBMiKvrT5x6vXp7TqeR7IOm3cke_hlHsLVkyuhqkATcSt2Oa9JvoNo2ZsgiptdeZXkjTTjU4X4kVmfwVCmpGCaCpoWVTpezsUNk6JMu15j0ybI6ycaQzeMIrIFH7cirTsLSjCCl3sUqfv9BaS8jVBRocyRUDH_YV9GU_tH-OImTZNlixJb6427rlXAz2JxnF00s1GLrSaEnJgL11KXBqv-m0Cy1vwS-zZkxAMUvXO1thc20qrG92lonYavMKJ9BwdryPEAtnZrOLYEUxt-JI2DPZa19h20H03ExuSA6YYy7UfrU-PvP9ygbDQGtAcqvt8NJLUvrkHdQeo9Ba_5F9mpIAvRU0NTUwE-vkP_iwMmHqHjyhy4HEUC9_IqEJTviV0CfmtB9sH06UAVVotMPEqbXJPGtt3P1Ler-HibqAZQAVB1vK87x2kVPNlLfgYj7jJhUZ5b4zm345a1WlrIUuDFLDO0kVYP8xk9Sxx7kyUDeHeJfGYpCX31TV9HlmFMucRsc29phwPuYkDfifUfnADOAgzO_OJFqTe9bTikm-BJPbuQoIwRR5Jdflf0_aFtLwki6rrNFk2kAo3mYTun-6tIqvsMgiLadfmC8BaE0rOC_FCW-YwrAbRTmA-oLYAa6LnCWRUsFU1AF7ogDQ-icOHeEyqq39Y4yQYr0CKCkrm84LPnz3G5yIABUQxB4iVzRNeHvuUn5sBrB6hFSYTTYmq5Rap4k37wJLa7YwOqSAiEXvTrHuC8NitkN7gGrSUsLPOc1gBycf16IKBwBeuaZRZsBgHfuB_lr2WsFLrcLXTIu0qTu0532HZ2bMBkbVkYo8AqEQ3niHqLKnNAecYbsELf1WP8XrN7nfWwJinHiYm43TlEOG6s2kHCxiG3ARu76BtGad2ambZIFdbrQqD67XMg5nwDA6jwDunUHtymjsff4CmtVkbVP6HtEAj_V0OdOFCgqcW29P_VlcDUjIrAJLcbui-TkLp0HJ_03WnW3nqylZWgv5InGRLicL7t-ZE_RXtQLBTMHD3RfiuHvruGf7TfZ7eG-XB7PDlb_F3C4uNXdjy8-heRjNgQxbd__pzI-30zddPRVfwP7euutKY-wnvrvmInt7DVJ8CbX9GL-Twao8POQJTaUr2Dv1Os66LHUCbE-DE9L5ca8D7gtYESrw-c64s0-oT4KaEzKc-NTswft_zPe9nVcve9JjhYGE65P7neDQH1Re-H7KEvWSL2lh0_yVexuGUUpk2SZzPHTTjAYdPVsnYXP-TkuhbB5oDrPdhXaTu-tKTHgWbxQewy5C0FCkbT_P-N_jnRgg8O_DvXVvpTfpVglXxRgau_83QCVIZhgWrgRs6jO1Y29WQpWz0YMB6oiX2KWYBB84rEBKJROlUYxPAMibBAOtzT12psu5yDM9xm0HzefKfavYj3uMWvexK5KEnJr7WyqAkVAO-mlfbiUxy8RsykIipiBwLllggNXFR-iyw4UNzHROCxCiimGSf6AzLFe9XQxpNrdnuggIHNqsy3ieH0HnaVM0qoo0BJr_t0ab6FXc3c_bCXa0kJ4KLYfAdEaYyYUaP_jTtv60Hd9UWAM6yfz5ThBi7WDAucv_HuqrzKKq6ptSz9yBVj7QXlZzuV1eilsJubp13MgA4NJbhuu6fWcf2s4_2UYCpnORBzRPaXI5q3jyvzTXhHOC2h6j04SKb7U2hplrOxZI3XTdI6AyW2HFyxF-wqBpvPwPsCOfAHlJi4z1iqs2lspjyeXnsSUz-ZJc0JQRlti0eYnGRowv-iFY_gPBtSlSBA9roK4erPjA2ZizfcpEYmOl71OIui8BapwDGd8kocjZWaqcQ-UhbEP5eMIOMW69PLEnZlfQmZHkZvc-hLl_p4CJtHQ1IbaUBl1a5DjYPFbHoTqn_hsgo3z3rOqmHlWJn2kz5weUQ8g&k=scRQhicv_0hE9aRWb3lIFMG1mNauV2nSW-Lgv5PwZhU22fHSYdZ266cSBcL2ePQv&al=f&ap=2",
                            "rate_source": 7,
                            "rendering_key": "f080a35d-de44-4879-a906-079a2a52ab36",
                            "replaces_carrier_id": null,
                            "semi_annual_estimate": 0
                        }],
                        "g": [{
                            "advert_position": 0,
                            "advert_priority": 1,
                            "advert_variation": 2,
                            "analytics_category": "Ads - Katch",
                            "best_seller_rank": 0,
                            "carrier_description": "",
                            "carrier_display_name": "Allstate",
                            "carrier_estimate_phone_number": null,
                            "carrier_featured_text": "Safe Drivers Choose Allstate&reg;",
                            "carrier_features": ["<ul><li>Safe Drivers Can Save Up To 45% On Their Auto Insurance</li><li>Get Two Safe Driver Bonus Checks a Year</li><li>Quote Online & Start Saving Today!</li></ul>"],
                            "carrier_icon": null,
                            "carrier_id": "katch",
                            "carrier_is_featured": false,
                            "carrier_legal_name": "Allstate",
                            "carrier_logo": "//cdn.katch.com/logos/adv_34807_401.gif?e=427ae720-1ebe-4044-af73-7a8c02384b1c_576186&pos=1",
                            "carrier_official_website": "www.Allstate.com",
                            "down_payment": 0,
                            "impression_html": "<img class=\"be_impr_html\" src=\"/be/i/t/?k=fc22465b-5874-41ce-a111-7ff3ea0597d1&al=g&ap=1&quote_id=5947e22ceff81d56b4a9e2e7\" />",
                            "insurance_product_id": null,
                            "insurance_product_name": null,
                            "insurance_product_not_match": false,
                            "is_advert": true,
                            "is_computed": false,
                            "is_coverage_mismatch": false,
                            "last_modified": "2017-06-22T09:39:27.565892",
                            "monetization_strategy": 4,
                            "monthly_estimate": 0,
                            "monthly_estimate_sub_text": "",
                            "purchase_method_affiliate_link": "/be/a/t/?p=k&r=FZqg3gZ2tQW-_lPAXYSt94D2jJPHZOWN-8aEqWH6NOvN3MRVCtrYCRBSrp1rXtD8fKmMEPcstMAbdjic33jn3vxTNkrlfH6MJVz55ljgbzp9oQIEHDko0CWT93lJYtavAutRzopPYt1-vaN0wRvFkNxk8LT_UO0O1twj3DNa5EYbNxvWCizF7QlqSi3dbINfIKLsTykVgIibj3E5bsHxIfUooR4yn1YacIPs_smK8sNA2iGmow3abyrlLAbh-X3Ut4NoYkDjXGRsmhjqsYC6dHxZ3fIh9BhGhT0tPIVhtAFb9hlY9NaXWtb1beXgN_epaZ0DHXt1fTHiSj82QT8jFWa3CivmUqKujgxiofovOwWmAzajwVVSakleN_OTL8YGbt64nIpCDmu8QRc1oGVph341lU7os1kGmSrltv3uPyosIlJuEWTwd8ECCIKQSVBSrjllDmN6loLOrncU55jI9vPkM15fLN2Th_mVqMYLcML7UTpbDIzAm8t6crewUPeUR_HQneKbIgrIQ2yA40p6oo45HzQQr6PP0gDLCcOjNCR31y8tojyxn1Bl849BINCqzS9RY_iETJSrpHJS-F5LlfkU9eKTteqa-97qP95KpHbeBT5nXeYzJKYEVql7f6EPXzIh2_AbnWjU8BoOPRYO8Go2LZf8u_Uk4XSPbBCtwviJ0DR1r3hexxWRc54JdhBfvRHcOcV2RVZmJZge9tfaNhptCJIEFFoRdvfYonbvQRYRsCrUlzSpf9qh60nBnIiNUDPlWoYWlfwF5CjaOi5n1BiueRquqzfIypAMZbG26ll0heYLVBQs9GtHCHYUlFNtFwbP69XfJP9RU4bm0wLp5cRx4wJEJx_bxv711qHSX1lQ8Vp2hGuy_9xGXdzMadUsV3_r7A-Kfhk6grAaRGMRj4V3hsag-cL72EcabuVMGXhSJ5a9ppL0Uf0qb7YPY7hjbW0XuOI_O3aSMYHNOpO7aa8jlDpQmRc7Pw1AeKmfvcDs3ZKpSFscnZmNu0rimGTTEruStR0QkVnIG3sso8eD5MEc5YzUv19GxxgmUqVyJLDtRULHDE_eI08m2OxHw8S73sydPZu59oPISo8NZ0ZQyqCc-YcGOI5sSycnMlm2NMn1k8BCjIP3gKBVaKJQ3sbvN1WuVVEcq4yHUSoScygT-uHFHUEjPoCgA8UXv3s6YvwYIA4pmlz-le9FacCtEu-YpnCIiOA2x76zuYzzVykBWhvcLjo5xzQ8LfDdHwNGNTQ=&k=hkWG-hgXU8VW-hH0vNZMOJEf13HPMcbmgN5aOmVzWZQEwJSJn0lVGMvfERf8WvzE&al=g&ap=1",
                            "rate_source": 7,
                            "rendering_key": "fc22465b-5874-41ce-a111-7ff3ea0597d1",
                            "replaces_carrier_id": 32,
                            "semi_annual_estimate": 0
                        }, {
                            "advert_position": 0,
                            "advert_priority": 1,
                            "advert_variation": 2,
                            "analytics_category": "Ads - MediaAlphaZebra",
                            "best_seller_rank": 0,
                            "carrier_description": "",
                            "carrier_display_name": "Esurance",
                            "carrier_estimate_phone_number": null,
                            "carrier_featured_text": "You Could Save with Esurance!",
                            "carrier_features": ["Minnesota Drivers - See If You Can Save Today<br>We've Insured Over 5 million Vehicles Since 1999<br>24/7 Claims Service - Located in the USA"],
                            "carrier_icon": null,
                            "carrier_id": "media_alpha",
                            "carrier_is_featured": false,
                            "carrier_legal_name": "Esurance",
                            "carrier_logo": "//d29u10q7qlh006.cloudfront.net/i/i/13/O2yQ5N5zaCrNIkKKJPX4MUykeew.png",
                            "carrier_official_website": "www.esurance.com",
                            "down_payment": 0,
                            "impression_html": "<img class=\"be_impr_html\" src=\"/be/i/t/?k=f080a35d-de44-4879-a906-079a2a52ab36&al=g&ap=2&quote_id=5947e22ceff81d56b4a9e2e7\" />",
                            "insurance_product_id": null,
                            "insurance_product_name": null,
                            "insurance_product_not_match": false,
                            "is_advert": true,
                            "is_computed": false,
                            "is_coverage_mismatch": false,
                            "last_modified": "2017-06-22T09:39:27.566209",
                            "monetization_strategy": 4,
                            "monthly_estimate": 0,
                            "monthly_estimate_sub_text": "",
                            "purchase_method_affiliate_link": "/be/a/t/?p=maz&r=IZCpvuh31KdcWPjeNGAAQzMhRiPEA2WmPRopeb9u-Qt-YRwV9RRburtu7RnwxI3k2rqOmhhR8IiMYfXEL40VpX_ijFZl4g96sAEXguaRm0mYesLjeHzg-_HN18appFmI63n8WRKU7tTkvknvaA056BE2U5asuZwGn6LC-sP266PbvyQrzasZeEBMiKvrT5x6vXp7TqeR7IOm3cke_hlHsLVkyuhqkATcSt2Oa9JvoNo2ZsgiptdeZXkjTTjU4X4kVmfwVCmpGCaCpoWVTpezsUNk6JMu15j0ybI6ycaQzeMIrIFH7cirTsLSjCCl3sUqfv9BaS8jVBRocyRUDH_YV9GU_tH-OImTZNlixJb6427rlXAz2JxnF00s1GLrSaEnJgL11KXBqv-m0Cy1vwS-zZkxAMUvXO1thc20qrG92lonYavMKJ9BwdryPEAtnZrOLYEUxt-JI2DPZa19h20H03ExuSA6YYy7UfrU-PvP9ygbDQGtAcqvt8NJLUvrkHdQeo9Ba_5F9mpIAvRU0NTUwE-vkP_iwMmHqHjyhy4HEUC9_IqEJTviV0CfmtB9sH06UAVVotMPEqbXJPGtt3P1Ler-HibqAZQAVB1vK87x2kVPNlLfgYj7jJhUZ5b4zm345a1WlrIUuDFLDO0kVYP8xk9Sxx7kyUDeHeJfGYpCX31TV9HlmFMucRsc29phwPuYkDfifUfnADOAgzO_OJFqTe9bTikm-BJPbuQoIwRR5Jdflf0_aFtLwki6rrNFk2kAo3mYTun-6tIqvsMgiLadfmC8BaE0rOC_FCW-YwrAbRTmA-oLYAa6LnCWRUsFU1AF7ogDQ-icOHeEyqq39Y4yQYr0CKCkrm84LPnz3G5yIABUQxB4iVzRNeHvuUn5sBrB6hFSYTTYmq5Rap4k37wJLa7YwOqSAiEXvTrHuC8NitkN7gGrSUsLPOc1gBycf16IKBwBeuaZRZsBgHfuB_lr2WsFLrcLXTIu0qTu0532HZ2bMBkbVkYo8AqEQ3niHqLKnNAecYbsELf1WP8XrN7nfWwJinHiYm43TlEOG6s2kHCxiG3ARu76BtGad2ambZIFdbrQqD67XMg5nwDA6jwDunUHtymjsff4CmtVkbVP6HtEAj_V0OdOFCgqcW29P_VlcDUjIrAJLcbui-TkLp0HJ_03WnW3nqylZWgv5InGRLicL7t-ZE_RXtQLBTMHD3RfiuHvruGf7TfZ7eG-XB7PDlb_F3C4uNXdjy8-heRjNgQxbd__pzI-30zddPRVfwP7euutKY-wnvrvmInt7DVJ8CbX9GL-Twao8POQJTaUr2Dv1Os66LHUCbE-DE9L5ca8D7gtYESrw-c64s0-oT4KaEzKc-NTswft_zPe9nVcve9JjhYGE65P7neDQH1Re-H7KEvWSL2lh0_yVexuGUUpk2SZzPHTTjAYdPVsnYXP-TkuhbB5oDrPdhXaTu-tKTHgWbxQewy5C0FCkbT_P-N_jnRgg8O_DvXVvpTfpVglXxRgau_83QCVIZhgWrgRs6jO1Y29WQpWz0YMB6oiX2KWYBB84rEBKJROlUYxPAMibBAOtzT12psu5yDM9xm0HzefKfavYj3uMWvexK5KEnJr7WyqAkVAO-mlfbiUxy8RsykIipiBwLllggNXFR-iyw4UNzHROCxCiimGSf6AzLFe9XQxpNrdnuggIHNqsy3ieH0HnaVM0qoo0BJr_t0ab6FXc3c_bCXa0kJ4KLYfAdEaYyYUaP_jTtv60Hd9UWAM6yfz5ThBi7WDAucv_HuqrzKKq6ptSz9yBVj7QXlZzuV1eilsJubp13MgA4NJbhuu6fWcf2s4_2UYCpnORBzRPaXI5q3jyvzTXhHOC2h6j04SKb7U2hplrOxZI3XTdI6AyW2HFyxF-wqBpvPwPsCOfAHlJi4z1iqs2lspjyeXnsSUz-ZJc0JQRlti0eYnGRowv-iFY_gPBtSlSBA9roK4erPjA2ZizfcpEYmOl71OIui8BapwDGd8kocjZWaqcQ-UhbEP5eMIOMW69PLEnZlfQmZHkZvc-hLl_p4CJtHQ1IbaUBl1a5DjYPFbHoTqn_hsgo3z3rOqmHlWJn2kz5weUQ8g&k=scRQhicv_0hE9aRWb3lIFMG1mNauV2nSW-Lgv5PwZhU22fHSYdZ266cSBcL2ePQv&al=g&ap=2",
                            "rate_source": 7,
                            "rendering_key": "f080a35d-de44-4879-a906-079a2a52ab36",
                            "replaces_carrier_id": null,
                            "semi_annual_estimate": 0
                        }]
                    }
                },
                "buy_quote_ref_id": "0FJEGUV1",
                "call_scheduled": null,
                "call_scheduled_for": null,
                "catv": "B",
                "channel_id": "3ACF01",
                "city": "Lakeville",
                "client_identifier": null,
                "coverage": 2,
                "coverage_gap": null,
                "coverage_selected": true,
                "credit_score": 1,
                "currently_insured": true,
                "dealer_name": null,
                "dealership_id": null,
                "discounts": null,
                "display_izzy_comments": null,
                "drivers": [{
                    "age": null,
                    "age_first_licensed": null,
                    "dob": "1992-10-09T19:00:00",
                    "driver_relationship": null,
                    "drivers_training": null,
                    "education": 2,
                    "employment": null,
                    "excluded": null,
                    "first_name": null,
                    "gender": 0,
                    "good_student": null,
                    "incidents": [],
                    "incidents_selected": false,
                    "is_student": false,
                    "last_name": null,
                    "marital_status": 0,
                    "other_applicable": null,
                    "primary_driver": true,
                    "uuid": null
                }],
                "email": "dddsdsd@msn.com",
                "email_modal_shown": null,
                "email_scheduled": null,
                "estimates": [{
                    "advert_position": null,
                    "advert_priority": null,
                    "advert_variation": 0,
                    "analytics_category": "",
                    "best_seller_rank": 0,
                    "bind_source": null,
                    "carrier_accepts_driver_dui": true,
                    "carrier_customer_score": "A+",
                    "carrier_description": "Liberty Mutual is committed to providing broad, useful and competitively-priced insurance products and services to meet their customers' ever-changing needs.",
                    "carrier_display_name": "Liberty Mutual",
                    "carrier_estimate_phone_number": "855-971-0501",
                    "carrier_featured_text": "",
                    "carrier_features": ["With Liberty Mutual you’ll receive:\r", "Guidance from a licensed insurance agent\r", "Outstanding customer service\r", "Insurance coverage from a Fortune 100 company"],
                    "carrier_financial_strength": "Excellent",
                    "carrier_has_bind_source": false,
                    "carrier_icon": "https://d3pbfr42of0pqo.cloudfront.net/carrier-icons/LM-Masterbrand-vert-blue_RGB_1.png",
                    "carrier_id": 16,
                    "carrier_is_featured": false,
                    "carrier_jd_power_score": "2",
                    "carrier_legal_name": "Liberty Mutual Insurance",
                    "carrier_official_website": "http://LIbertyMutual.com/",
                    "down_payment": 0,
                    "insurance_product_id": 3693,
                    "insurance_product_name": "Liberty Mutual",
                    "insurance_product_not_match": true,
                    "is_advert": false,
                    "is_computed": true,
                    "is_coverage_mismatch": false,
                    "is_q2b": false,
                    "last_modified": "2017-06-22T09:38:34.651686",
                    "market_segment_id": 939464,
                    "monetization_strategy": 1,
                    "monthly_estimate": 0,
                    "monthly_estimate_sub_text": "",
                    "purchase_method_affiliate_link": null,
                    "rate_source": 17,
                    "semi_annual_estimate": 0
                }, {
                    "advert_position": null,
                    "advert_priority": null,
                    "advert_variation": 0,
                    "analytics_category": "",
                    "best_seller_rank": 0,
                    "bind_source": null,
                    "carrier_accepts_driver_dui": true,
                    "carrier_customer_score": "A-",
                    "carrier_description": "MetLife Auto & Home MyDirect’s 100% digital experience lets you easily buy and manage your policy all online. It’s the first of its kind and backed by the experience of MetLife Auto & Home.",
                    "carrier_display_name": "MetLife",
                    "carrier_estimate_phone_number": "855-969-5390",
                    "carrier_featured_text": "",
                    "carrier_features": ["Budget friendly\r", "100% online via MetLife Auto & Home MyDirect\r", "Hassle-free click to chat assistance\r", "Convenient payment options\r", "Coverage from a company you know and trust"],
                    "carrier_financial_strength": "Superior",
                    "carrier_has_bind_source": false,
                    "carrier_icon": "https://d3pbfr42of0pqo.cloudfront.net/carrier-icons/metlife_eng_logo_rgb.png",
                    "carrier_id": 87,
                    "carrier_is_featured": false,
                    "carrier_jd_power_score": "3",
                    "carrier_legal_name": "Metropolitan Insurance Service Consultants, Inc.",
                    "carrier_official_website": "https://www.metlife.com/individual/index.html",
                    "down_payment": 0,
                    "insurance_product_id": 3616,
                    "insurance_product_name": "MetLife",
                    "insurance_product_not_match": true,
                    "is_advert": false,
                    "is_computed": true,
                    "is_coverage_mismatch": false,
                    "is_q2b": false,
                    "last_modified": "2017-06-22T09:39:21.580037",
                    "market_segment_id": 939464,
                    "monetization_strategy": 1,
                    "monthly_estimate": 0,
                    "monthly_estimate_sub_text": "",
                    "purchase_method_affiliate_link": "",
                    "rate_source": 18,
                    "semi_annual_estimate": 0
                }, {
                    "advert_position": null,
                    "advert_priority": null,
                    "advert_variation": 0,
                    "analytics_category": "",
                    "best_seller_rank": 0,
                    "bind_source": null,
                    "carrier_accepts_driver_dui": true,
                    "carrier_customer_score": "A",
                    "carrier_description": "Allied Insurance, a Nationwide company, offers a variety of packages with customizable coverages, discounts, benefits and rewards to make sure your insurance is right for you.",
                    "carrier_display_name": "Allied",
                    "carrier_estimate_phone_number": "855-969-5390",
                    "carrier_featured_text": "",
                    "carrier_features": ["Mobile Friendly\r", "Manage Your Policy Online\r", "Lock In Your Rates\r", "Accident Forgiveness\r", "Vanishing Deductible\r", "Roadside Assistance Packages"],
                    "carrier_financial_strength": "Excellent",
                    "carrier_has_bind_source": false,
                    "carrier_icon": "",
                    "carrier_id": 78,
                    "carrier_is_featured": false,
                    "carrier_jd_power_score": "3",
                    "carrier_legal_name": "Allied Insurance",
                    "carrier_official_website": "http://www.alliedinsurance.com/",
                    "down_payment": 0,
                    "insurance_product_id": 3244,
                    "insurance_product_name": "Allied AMCO PPAM",
                    "insurance_product_not_match": false,
                    "is_advert": false,
                    "is_computed": true,
                    "is_coverage_mismatch": false,
                    "is_q2b": false,
                    "last_modified": "2017-06-22T09:39:24.915550",
                    "market_segment_id": 939464,
                    "monetization_strategy": 1,
                    "monthly_estimate": 185.91666666666666,
                    "monthly_estimate_sub_text": "",
                    "purchase_method_affiliate_link": null,
                    "rate_source": 0,
                    "semi_annual_estimate": 1115.5
                }, {
                    "advert_position": null,
                    "advert_priority": null,
                    "advert_variation": 0,
                    "analytics_category": "",
                    "best_seller_rank": 0,
                    "bind_source": null,
                    "carrier_accepts_driver_dui": true,
                    "carrier_customer_score": "B+",
                    "carrier_description": "Get the protection you need at a price you can afford with State Farm; offering packaged options, discounts and custom coverage to meet any driver's needs.",
                    "carrier_display_name": "State Farm",
                    "carrier_estimate_phone_number": "855-969-5469",
                    "carrier_featured_text": "",
                    "carrier_features": ["Mobile Friendly\r", "Manage Your Account Online\r", "24x7 Support\r", "Steer Clear Safe Driver Course\r", "Drive Safe & Save Program\r", "Emergency Road Service\r", "Rental Car Coverage\r", "Travel Expenses Coverage"],
                    "carrier_financial_strength": "Superior",
                    "carrier_has_bind_source": false,
                    "carrier_icon": "",
                    "carrier_id": 18,
                    "carrier_is_featured": false,
                    "carrier_jd_power_score": "3",
                    "carrier_legal_name": "State Farm Mutual Automobile Insurance Company",
                    "carrier_official_website": "http://StateFarm.com/",
                    "down_payment": 0,
                    "insurance_product_id": 279,
                    "insurance_product_name": "State Farm Mutual Auto",
                    "insurance_product_not_match": false,
                    "is_advert": false,
                    "is_computed": true,
                    "is_coverage_mismatch": false,
                    "is_q2b": false,
                    "last_modified": "2017-06-22T09:39:24.810351",
                    "market_segment_id": 939464,
                    "monetization_strategy": 1,
                    "monthly_estimate": 201.0,
                    "monthly_estimate_sub_text": "",
                    "purchase_method_affiliate_link": "http://track.flexlinks.com/a.ashx?foid=1052077.323155&fot=9999&foc=1&fobs=",
                    "rate_source": 0,
                    "semi_annual_estimate": 1206.0
                }, {
                    "advert_position": null,
                    "advert_priority": null,
                    "advert_variation": 0,
                    "analytics_category": "",
                    "best_seller_rank": 0,
                    "bind_source": null,
                    "carrier_accepts_driver_dui": true,
                    "carrier_customer_score": "A",
                    "carrier_description": "Nationwide demonstrates customer appreciation and respect through dedicated, licensed professionals and superior claim service.",
                    "carrier_display_name": "Nationwide",
                    "carrier_estimate_phone_number": "855-712-8879",
                    "carrier_featured_text": "",
                    "carrier_features": ["Mobile Friendly\r", "Manage Your Account Online\r", "24x7 Support\r", "Report Claims Online\r", "Vanishing Deductible\r", "Accident Forgiveness\r", "Gap Insurance\r", "Roadside Assistance\r", "Towing & Labor\r", "Rental Reimbursement"],
                    "carrier_financial_strength": "Superior",
                    "carrier_has_bind_source": false,
                    "carrier_icon": "",
                    "carrier_id": 15,
                    "carrier_is_featured": false,
                    "carrier_jd_power_score": "3",
                    "carrier_legal_name": "Nationwide Mutual Insurance Company",
                    "carrier_official_website": "http://nationwide.com/",
                    "down_payment": 0,
                    "insurance_product_id": 617,
                    "insurance_product_name": "NICOA",
                    "insurance_product_not_match": false,
                    "is_advert": false,
                    "is_computed": true,
                    "is_coverage_mismatch": false,
                    "is_q2b": false,
                    "last_modified": "2017-06-22T09:39:25.056958",
                    "market_segment_id": 939464,
                    "monetization_strategy": 1,
                    "monthly_estimate": 209.83333333333334,
                    "monthly_estimate_sub_text": "",
                    "purchase_method_affiliate_link": null,
                    "rate_source": 0,
                    "semi_annual_estimate": 1259.0
                }, {
                    "advert_position": null,
                    "advert_priority": null,
                    "advert_variation": 0,
                    "analytics_category": null,
                    "best_seller_rank": 0,
                    "bind_source": null,
                    "carrier_accepts_driver_dui": true,
                    "carrier_customer_score": "A+",
                    "carrier_description": "General Casualty Insurance, purchased by QBE in 2007, offers affordable auto insurance rates and reviews every policy at renewal to reward responsible drivers with their most competitive rates.",
                    "carrier_display_name": "General Casualty",
                    "carrier_estimate_phone_number": "855-969-5390",
                    "carrier_featured_text": null,
                    "carrier_features": ["Manage Your Policy Online\r", "Pay Online\r", "Towing & Labor Coverage\r", "Accident Forgiveness Program"],
                    "carrier_financial_strength": "Excellent",
                    "carrier_has_bind_source": false,
                    "carrier_icon": "",
                    "carrier_id": 166,
                    "carrier_is_featured": false,
                    "carrier_jd_power_score": "Not Rated",
                    "carrier_legal_name": "General Casualty",
                    "carrier_official_website": "http://qbena.com/",
                    "down_payment": 0,
                    "insurance_product_id": 2130,
                    "insurance_product_name": "General Cas FlexAuto",
                    "insurance_product_not_match": false,
                    "is_advert": false,
                    "is_computed": true,
                    "is_coverage_mismatch": false,
                    "is_q2b": false,
                    "last_modified": "2017-06-22T09:39:24.962247",
                    "market_segment_id": 939464,
                    "monetization_strategy": 1,
                    "monthly_estimate": 238.33333333333334,
                    "monthly_estimate_sub_text": null,
                    "purchase_method_affiliate_link": null,
                    "rate_source": 0,
                    "semi_annual_estimate": 1430.0
                }, {
                    "advert_position": null,
                    "advert_priority": null,
                    "advert_variation": 0,
                    "analytics_category": null,
                    "best_seller_rank": 0,
                    "bind_source": null,
                    "carrier_accepts_driver_dui": true,
                    "carrier_customer_score": "A+",
                    "carrier_description": "Farm Bureau Mutual of Iowa focuses on building trusted relationships and helping you protect what matters most, so they can help you find the right products at the right time as you work to achieve your goals.",
                    "carrier_display_name": "Farm Bureau Mutual (IA Group)",
                    "carrier_estimate_phone_number": "855-969-5390",
                    "carrier_featured_text": null,
                    "carrier_features": ["Manage Your Policy Online\r", "24x7 Support\r", "Report Claims Online\r", "One Deductible Advantage\r", "Emergency Roadside Coverage\r", "Rental Reimbursement Coverage\r", "Trailer Personal Effects Coverage\r", "Identity Services & Fraud Protection"],
                    "carrier_financial_strength": "Excellent",
                    "carrier_has_bind_source": false,
                    "carrier_icon": "",
                    "carrier_id": 83,
                    "carrier_is_featured": false,
                    "carrier_jd_power_score": "Not Rated",
                    "carrier_legal_name": "Farm Bureau Mutual (IA Group)",
                    "carrier_official_website": "http://www.fbfs.com/content/insurance/",
                    "down_payment": 0,
                    "insurance_product_id": 1601,
                    "insurance_product_name": "Western Agricultural Ins. Co.",
                    "insurance_product_not_match": false,
                    "is_advert": false,
                    "is_computed": true,
                    "is_coverage_mismatch": true,
                    "is_q2b": false,
                    "last_modified": "2017-06-22T09:39:25.035584",
                    "market_segment_id": 939464,
                    "monetization_strategy": 1,
                    "monthly_estimate": 241.16666666666666,
                    "monthly_estimate_sub_text": null,
                    "purchase_method_affiliate_link": null,
                    "rate_source": 0,
                    "semi_annual_estimate": 1447.0
                }, {
                    "advert_position": null,
                    "advert_priority": null,
                    "advert_variation": 0,
                    "analytics_category": "",
                    "best_seller_rank": 0,
                    "bind_source": null,
                    "carrier_accepts_driver_dui": true,
                    "carrier_customer_score": "A-",
                    "carrier_description": "Farmers Auto Insurance knows that protecting your vehicle is more than just a basic obligation, which is why they provide all the value and flexibility you need, along with unparalleled customer and claim service.",
                    "carrier_display_name": "Farmers",
                    "carrier_estimate_phone_number": "855-342-5816",
                    "carrier_featured_text": "",
                    "carrier_features": ["Manage Your Policy Online\r", "24x7 Support\r", "Paperless Policy Option\r", "Accident Forgiveness\r", "New Car Replacement Coverage\r", "Mobile Glass Repair Services\r", "Towing & Roadside Assistance Coverage\r", "Car Rental Reimbursement Coverage"],
                    "carrier_financial_strength": "Excellent",
                    "carrier_has_bind_source": false,
                    "carrier_icon": "",
                    "carrier_id": 10,
                    "carrier_is_featured": false,
                    "carrier_jd_power_score": "3",
                    "carrier_legal_name": "Farmers Insurance Group",
                    "carrier_official_website": "http://www.farmers.com/auto/",
                    "down_payment": 0,
                    "insurance_product_id": 69,
                    "insurance_product_name": "Illinois Farmers Ins",
                    "insurance_product_not_match": false,
                    "is_advert": false,
                    "is_computed": true,
                    "is_coverage_mismatch": false,
                    "is_q2b": false,
                    "last_modified": "2017-06-22T09:39:24.834544",
                    "market_segment_id": 939464,
                    "monetization_strategy": 1,
                    "monthly_estimate": 244.33333333333334,
                    "monthly_estimate_sub_text": "",
                    "purchase_method_affiliate_link": null,
                    "rate_source": 0,
                    "semi_annual_estimate": 1466.0
                }, {
                    "advert_position": null,
                    "advert_priority": null,
                    "advert_variation": 0,
                    "analytics_category": "",
                    "best_seller_rank": 0,
                    "bind_source": null,
                    "carrier_accepts_driver_dui": true,
                    "carrier_customer_score": "A+",
                    "carrier_description": "Farmers Union Insurance, a member of the QBE Insurance Group, is known for their fairness, rural values, personalized service and long-standing relationships.",
                    "carrier_display_name": "Farmers Union Insurance  ",
                    "carrier_estimate_phone_number": "855-969-5390",
                    "carrier_featured_text": "",
                    "carrier_features": ["Pay Online\r", "Accident Forgiveness"],
                    "carrier_financial_strength": "Excellent",
                    "carrier_has_bind_source": false,
                    "carrier_icon": "",
                    "carrier_id": 93,
                    "carrier_is_featured": false,
                    "carrier_jd_power_score": "Not Rated",
                    "carrier_legal_name": "National Farmers Union Property and Casualty Company or QBE Farmers Union Insurance",
                    "carrier_official_website": "http://www.farmersunioninsurance.com/",
                    "down_payment": 0,
                    "insurance_product_id": 1760,
                    "insurance_product_name": "Farmers Union P&C",
                    "insurance_product_not_match": false,
                    "is_advert": false,
                    "is_computed": true,
                    "is_coverage_mismatch": false,
                    "is_q2b": false,
                    "last_modified": "2017-06-22T09:39:24.800003",
                    "market_segment_id": 939464,
                    "monetization_strategy": 1,
                    "monthly_estimate": 248.33333333333334,
                    "monthly_estimate_sub_text": "",
                    "purchase_method_affiliate_link": null,
                    "rate_source": 0,
                    "semi_annual_estimate": 1490.0
                }, {
                    "advert_position": null,
                    "advert_priority": null,
                    "advert_variation": 0,
                    "analytics_category": "",
                    "best_seller_rank": 0,
                    "bind_source": null,
                    "carrier_accepts_driver_dui": true,
                    "carrier_customer_score": "B+",
                    "carrier_description": "American Family strives to provide their customers with industry-leading service, an exceptional claims experience and products that build long-term relationships.",
                    "carrier_display_name": "American Family",
                    "carrier_estimate_phone_number": "855-969-5390",
                    "carrier_featured_text": "",
                    "carrier_features": ["Manage Your Policy Online\r", "24x7 Support\r", "Emergency Road Service \r", "Teen Safe Driver Program"],
                    "carrier_financial_strength": "Excellent",
                    "carrier_has_bind_source": false,
                    "carrier_icon": "",
                    "carrier_id": 62,
                    "carrier_is_featured": false,
                    "carrier_jd_power_score": "4",
                    "carrier_legal_name": "American Family Insurance",
                    "carrier_official_website": "http://www.amfam.com/",
                    "down_payment": 0,
                    "insurance_product_id": 233,
                    "insurance_product_name": "American Family Mutual",
                    "insurance_product_not_match": false,
                    "is_advert": false,
                    "is_computed": true,
                    "is_coverage_mismatch": false,
                    "is_q2b": false,
                    "last_modified": "2017-06-22T09:39:24.889067",
                    "market_segment_id": 939464,
                    "monetization_strategy": 1,
                    "monthly_estimate": 269.0833333333333,
                    "monthly_estimate_sub_text": "",
                    "purchase_method_affiliate_link": null,
                    "rate_source": 0,
                    "semi_annual_estimate": 1614.5
                }, {
                    "advert_position": null,
                    "advert_priority": null,
                    "advert_variation": 0,
                    "analytics_category": null,
                    "best_seller_rank": 0,
                    "bind_source": null,
                    "carrier_accepts_driver_dui": true,
                    "carrier_customer_score": "A+",
                    "carrier_description": "Western National Insurance offers excellent personal auto coverage at a fair price, matched with experienced claim staff that is ready to provide outstanding service.",
                    "carrier_display_name": "Western National",
                    "carrier_estimate_phone_number": "855-969-5390",
                    "carrier_featured_text": null,
                    "carrier_features": ["Mobile Friendly\r", "24x7 Support\r", "Manage Your Account Online\r", "No Surcharge Promise\r", "Rental Reimbursement Coverage\r", "Towing & Labor Coverage\r", "Full Glass Coverage\r", "Audio/Visual/Data Electronic Equipment Coverage\r", "Roadside Assistance\r", "New Vehicle Replacement Cost Coverage"],
                    "carrier_financial_strength": "Excellent",
                    "carrier_has_bind_source": false,
                    "carrier_icon": "",
                    "carrier_id": 85,
                    "carrier_is_featured": false,
                    "carrier_jd_power_score": "Not Rated",
                    "carrier_legal_name": "Western National Insurance Group",
                    "carrier_official_website": "http://www.wnins.com/",
                    "down_payment": 0,
                    "insurance_product_id": 430,
                    "insurance_product_name": "Western National Mutual",
                    "insurance_product_not_match": false,
                    "is_advert": false,
                    "is_computed": true,
                    "is_coverage_mismatch": false,
                    "is_q2b": false,
                    "last_modified": "2017-06-22T09:39:25.010657",
                    "market_segment_id": 939464,
                    "monetization_strategy": 1,
                    "monthly_estimate": 282.6666666666667,
                    "monthly_estimate_sub_text": null,
                    "purchase_method_affiliate_link": null,
                    "rate_source": 0,
                    "semi_annual_estimate": 1696.0
                }, {
                    "advert_position": null,
                    "advert_priority": null,
                    "advert_variation": 0,
                    "analytics_category": null,
                    "best_seller_rank": 0,
                    "bind_source": null,
                    "carrier_accepts_driver_dui": true,
                    "carrier_customer_score": "A+",
                    "carrier_description": "West Bend Auto Insurance seeks to provide peace of mind through sound insurance and exceptional service by covering your vehicles and home on one policy; this means more coverages for your vehicle and only one premium to pay.",
                    "carrier_display_name": "West Bend Mutual",
                    "carrier_estimate_phone_number": "855-969-5390",
                    "carrier_featured_text": null,
                    "carrier_features": ["24x7 Support\r", "Pay Online\r", "24-Hour Emergency Roadside Service\r", "Classic Car Coverage\r", "Referral Rewards\r", "Claim Free Cash Back Award"],
                    "carrier_financial_strength": "Excellent",
                    "carrier_has_bind_source": false,
                    "carrier_icon": "",
                    "carrier_id": 92,
                    "carrier_is_featured": false,
                    "carrier_jd_power_score": "Not Rated",
                    "carrier_legal_name": "West Bend Mutual Insurance Company",
                    "carrier_official_website": "http://www.thesilverlining.com/",
                    "down_payment": 0,
                    "insurance_product_id": 1510,
                    "insurance_product_name": "West Bend Mut H&H Elite",
                    "insurance_product_not_match": false,
                    "is_advert": false,
                    "is_computed": true,
                    "is_coverage_mismatch": false,
                    "is_q2b": false,
                    "last_modified": "2017-06-22T09:39:24.851740",
                    "market_segment_id": 939464,
                    "monetization_strategy": 1,
                    "monthly_estimate": 296.0,
                    "monthly_estimate_sub_text": null,
                    "purchase_method_affiliate_link": null,
                    "rate_source": 0,
                    "semi_annual_estimate": 1776.0
                }, {
                    "advert_position": null,
                    "advert_priority": null,
                    "advert_variation": 0,
                    "analytics_category": "",
                    "best_seller_rank": 0,
                    "bind_source": null,
                    "carrier_accepts_driver_dui": true,
                    "carrier_customer_score": "A",
                    "carrier_description": "Allstate gives quality protection at a great price, complete with personal attention and service you need to choose coverage that makes the most sense for you.",
                    "carrier_display_name": "Allstate",
                    "carrier_estimate_phone_number": "855-729-2408",
                    "carrier_featured_text": "",
                    "carrier_features": ["Mobile Friendly\r", "24x7 Support\r", "Manage Your Account Online\r", "Accident Forgiveness\r", "Drivewise Usage Tracking App\r", "Star Driver Teen Driving Program\r", "Towing & Labor Coverage"],
                    "carrier_financial_strength": "Superior",
                    "carrier_has_bind_source": false,
                    "carrier_icon": "",
                    "carrier_id": 32,
                    "carrier_is_featured": false,
                    "carrier_jd_power_score": "3",
                    "carrier_legal_name": "Allstate",
                    "carrier_official_website": "http://www.allstate.com/",
                    "down_payment": 0,
                    "insurance_product_id": 201,
                    "insurance_product_name": "Allstate Indemnity",
                    "insurance_product_not_match": false,
                    "is_advert": false,
                    "is_computed": true,
                    "is_coverage_mismatch": false,
                    "is_q2b": false,
                    "last_modified": "2017-06-22T09:39:25.075237",
                    "market_segment_id": 939464,
                    "monetization_strategy": 1,
                    "monthly_estimate": 346.0833333333333,
                    "monthly_estimate_sub_text": "",
                    "purchase_method_affiliate_link": null,
                    "rate_source": 0,
                    "semi_annual_estimate": 2076.5
                }, {
                    "advert_position": null,
                    "advert_priority": null,
                    "advert_variation": 0,
                    "analytics_category": null,
                    "best_seller_rank": 0,
                    "bind_source": null,
                    "carrier_accepts_driver_dui": true,
                    "carrier_customer_score": "B-",
                    "carrier_description": "Along with great rates and some of the best claims service around, Country Financial offers a variety of ways to customize your car insurance so you can cruise the road with confidence.",
                    "carrier_display_name": "Country",
                    "carrier_estimate_phone_number": "855-969-5390",
                    "carrier_featured_text": null,
                    "carrier_features": ["Manage Your Policy Online\r", "Emergency Road Service Coverage\r", "Rental Car Coverage\r", "Trip Interruption Coverage\r", "Safety Glass Coverage\r", "Personal Effects Coverage\r", "Renters Coverage"],
                    "carrier_financial_strength": "Superior",
                    "carrier_has_bind_source": false,
                    "carrier_icon": "",
                    "carrier_id": 74,
                    "carrier_is_featured": false,
                    "carrier_jd_power_score": "3",
                    "carrier_legal_name": "Country Financial",
                    "carrier_official_website": "http://www.countryfinancial.com/",
                    "down_payment": 0,
                    "insurance_product_id": 2900,
                    "insurance_product_name": "Country Casualty",
                    "insurance_product_not_match": false,
                    "is_advert": false,
                    "is_computed": true,
                    "is_coverage_mismatch": false,
                    "is_q2b": false,
                    "last_modified": "2017-06-22T09:39:24.990712",
                    "market_segment_id": 939464,
                    "monetization_strategy": 1,
                    "monthly_estimate": 358.3333333333333,
                    "monthly_estimate_sub_text": null,
                    "purchase_method_affiliate_link": null,
                    "rate_source": 0,
                    "semi_annual_estimate": 2150.0
                }, {
                    "advert_position": null,
                    "advert_priority": null,
                    "advert_variation": 0,
                    "analytics_category": "",
                    "best_seller_rank": 0,
                    "bind_source": null,
                    "carrier_accepts_driver_dui": true,
                    "carrier_customer_score": "A+",
                    "carrier_description": "Since the company was founded, Encompass Insurance has focused solely on personal insurance policies and continues to provide their customers with hassle-free claims and the simple promise of protection and security.",
                    "carrier_display_name": "Encompass",
                    "carrier_estimate_phone_number": "855-969-5390",
                    "carrier_featured_text": "",
                    "carrier_features": ["Mobile Friendly\r", "24x7 Support\r", "Pay Online\r", "Accident Forgiveness\r", "New Car Replacement Coverage\r", "Rental Reimbursement Coverage\r", "Roadside Assistance Coverage"],
                    "carrier_financial_strength": "Superior",
                    "carrier_has_bind_source": false,
                    "carrier_icon": "",
                    "carrier_id": 3,
                    "carrier_is_featured": false,
                    "carrier_jd_power_score": "Not Rated",
                    "carrier_legal_name": "Encompass Insurance Company",
                    "carrier_official_website": "http://www.encompassinsurance.com/",
                    "down_payment": 0,
                    "insurance_product_id": 2375,
                    "insurance_product_name": "Encompass Indemnity",
                    "insurance_product_not_match": false,
                    "is_advert": false,
                    "is_computed": true,
                    "is_coverage_mismatch": false,
                    "is_q2b": false,
                    "last_modified": "2017-06-22T09:39:24.904169",
                    "market_segment_id": 939464,
                    "monetization_strategy": 1,
                    "monthly_estimate": 464.1666666666667,
                    "monthly_estimate_sub_text": "",
                    "purchase_method_affiliate_link": null,
                    "rate_source": 0,
                    "semi_annual_estimate": 2785.0
                }, {
                    "advert_position": null,
                    "advert_priority": null,
                    "advert_variation": 0,
                    "analytics_category": "",
                    "best_seller_rank": 0,
                    "bind_source": null,
                    "carrier_accepts_driver_dui": true,
                    "carrier_customer_score": "A+",
                    "carrier_description": "North Star Mutual provides insurance protection through a variety of products along with friendly personal service and fast, hassle-free claims handling to keep you on course.",
                    "carrier_display_name": "North Star Mutual",
                    "carrier_estimate_phone_number": "855-969-5390",
                    "carrier_featured_text": "",
                    "carrier_features": ["Pay Online\r", "Pet Injury Protection\r", "Rental Reimbursement\r", "Roadside Assistance\r", "Customization Coverage\r", "Safety Glass Coverage"],
                    "carrier_financial_strength": "Superior",
                    "carrier_has_bind_source": false,
                    "carrier_icon": "",
                    "carrier_id": 96,
                    "carrier_is_featured": false,
                    "carrier_jd_power_score": "Not Rated",
                    "carrier_legal_name": "North Star",
                    "carrier_official_website": "http://www.nstarco.com/nsmic/default.aspx",
                    "down_payment": 0,
                    "insurance_product_id": 2285,
                    "insurance_product_name": "North Star Mutual",
                    "insurance_product_not_match": false,
                    "is_advert": false,
                    "is_computed": true,
                    "is_coverage_mismatch": false,
                    "is_q2b": false,
                    "last_modified": "2017-06-22T09:39:24.972754",
                    "market_segment_id": 939464,
                    "monetization_strategy": 1,
                    "monthly_estimate": 495.8333333333333,
                    "monthly_estimate_sub_text": "",
                    "purchase_method_affiliate_link": null,
                    "rate_source": 0,
                    "semi_annual_estimate": 2975.0
                }],
                "experiment_id": null,
                "extended_pip_type": null,
                "external_id": null,
                "facebook_share": null,
                "first_name": "dddd",
                "first_party_medical_benefit": null,
                "gclid": null,
                "google_share": null,
                "has_completed_driver": null,
                "has_completed_mdv": true,
                "has_completed_roadblock": false,
                "has_completed_vehicle": null,
                "has_coverage_completed": null,
                "has_entered_app": true,
                "home_ownership": 0,
                "id": "5947e22ceff81d56b4a9e2e7",
                "include_wage_loss": null,
                "internal_id": null,
                "ip_address": "197.149.67.66",
                "is_coverage_shown": null,
                "is_dealer_quote": false,
                "is_email_modal_open": null,
                "is_mobile": true,
                "is_referral": false,
                "izzys_last_comment": null,
                "keyword": null,
                "last_name": "sdsd",
                "lead_quote_id": null,
                "liability_coverage": null,
                "location_id": null,
                "medical_payment_coverage": null,
                "medium": null,
                "mobile_driver_count": 1,
                "mobile_vehicle_count": 1,
                "multi_policy_discount": null,
                "nationwide_quote_id": null,
                "non_owner": null,
                "partner_data": {
                    "Liberty Mutual": {
                        "driver_insurer_ids": {
                            "Drv1": "3511558329712.000"
                        },
                        "insured_or_principal_id": "3511558329712.000",
                        "policy_level_id": "3281564909081",
                        "vehicle_insurer_ids": {
                            "Veh1": "116924415570336"
                        }
                    }
                },
                "phone_number": "4155552671",
                "pip_coverage": null,
                "pip_coverage_type": null,
                "pip_deductible": null,
                "pip_deductible_option": null,
                "poll_for_estimates": false,
                "prior_carrier": 1,
                "prior_carrier_coverage_months": 12,
                "prior_insurance_expiration_date": null,
                "prior_liability_limit": null,
                "property_damage_coverage": null,
                "requires_sr22": null,
                "resource_uri": "/api/internal/v1/quote/5947e22ceff81d56b4a9e2e7/",
                "session_id": "b95sbd27y4rge3s9m64izxfpdqlst1vb",
                "sms_scheduled": null,
                "source": null,
                "state": "MN",
                "subid": null,
                "subid2": null,
                "subid3": null,
                "subid4": null,
                "subid5": null,
                "subid6": null,
                "subid7": null,
                "term": null,
                "tort": null,
                "twitter_share": null,
                "umpd_coverage": null,
                "umpd_deductible": null,
                "uninsured_motorist_coverage": null,
                "unique_visitor_id": null,
                "update_num": 0,
                "use_rpi_ad_sort": false,
                "user_agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1",
                "vehicles": [{
                    "collision": null,
                    "comprehensive": null,
                    "garaging_address": null,
                    "has_alarm": null,
                    "make": "BMW",
                    "miles_per_year": null,
                    "model": "7 Series",
                    "ownership": 2,
                    "primary_use": null,
                    "rental_limit": null,
                    "submodel": "740i 4dr Sedan",
                    "towing_limit": null,
                    "vehicle_display_name": null,
                    "vehicle_id": 125437,
                    "vin": null,
                    "year": 2011
                }],
                "zipcode": "55044"
            },
            zebra_questions : null,
            claims : [],
            policies : []
        };
    }
    if(action.type === 'STUFF_CHANGED'){
        let newState = state;
        newState[action.data.key] =  action.data.value;
        return newState;
    }
    if(action.type === 'NEW_CLAIM'){
        let newState = state;
        newState.claims.push(action.data.value);
        return newState;
    }
    if(action.type === 'NEW_POLICY'){
        let newState = state;
        newState.policies.push(action.data.value);
        return newState;
    }
    return state;
};
export default reducer;